Using Theano backend.
v3: < -2.81224, -1.39613, 0.000325715 > v4: < -0.107162, 2.21777, 2.57149e-05 >
v3: < -2.84796, -0.656991, 0.000334285 > v4: < 0.107162, -2.21777, -2.57149e-05 >
v3: < -0.762735, 0.269438, 3.01791 > v4: < 1.03538e-10, -1.47466e-09, -3.0622e-10 >
v3: < -0.813486, 0.992276, 3.16801 > v4: < -1.03538e-10, 1.47466e-09, 3.0622e-10 >
v3: < 0.0781591, -1.85981, 0.238697 > v4: < 1.75109, 0.211954, 0.238157 >
v3: < 0.806191, -1.77168, 0.337713 > v4: < -1.75109, -0.211954, -0.238157 >
v3: < 0.751736, -0.11729, -3.15812 > v4: < -5.62308e-10, -5.66057e-11, -7.96001e-10 >
v3: < 1.17798, -0.0743816, -2.55473 > v4: < 5.62308e-10, 5.66057e-11, 7.96001e-10 >
v3: < -3.99454, -0.735413, 0.000108009 > v4: < 0.734252, 1.62205, 0.000178009 >
v3: < -3.68937, -0.0612667, 0.000181991 > v4: < -0.734252, -1.62205, -0.000178009 >
v3: < -0.803722, 1.75859, 3.08192 > v4: < -3.95405e-10, -1.5474e-10, -8.97555e-10 >
v3: < -0.509037, 1.87391, 3.75085 > v4: < 3.95405e-10, 1.5474e-10, 8.97555e-10 >
v3: < -3.68366, 0.118962, 0.000195258 > v4: < 1.1646, 0.00391211, 0.000235258 >
v3: < -2.94366, 0.121448, 0.000344742 > v4: < -1.1646, -0.00391211, -0.000235258 >
v3: < 0.21516, 4.84703, -2.27474 > v4: < 7.95373e-10, -1.58489e-10, 3.64512e-10 >
v3: < 0.877106, 4.71513, -1.97137 > v4: < -7.95373e-10, 1.58488e-10, -3.64512e-10 >
v3: < -4.77067, -1.49077, -5.94841e-05 > v4: < -0.0418777, 0.866686, 1.05159e-05 >
v3: < -4.80638, -0.751636, -5.05159e-05 > v4: < 0.0418777, -0.866686, -1.05159e-05 >
v3: < -0.0549074, 0.00538787, -2.98157 > v4: < -2.71984e-09, 3.75411e-09, -1.62472e-10 >
v3: < -0.488799, 0.604276, -3.00749 > v4: < 2.71984e-09, -3.75411e-09, 1.62472e-10 >
v3: < -0.416796, -2.72066, 0.250581 > v4: < 2.28828, 0.893235, 0.250281 >
v3: < 0.268996, -2.45297, 0.325589 > v4: < -2.28828, -0.893235, -0.250281 >
v3: < 1.54295, -0.192881, 2.87238 > v4: < -6.82178e-10, -4.36923e-10, 5.62132e-10 >
v3: < 2.05491, 0.135022, 2.45051 > v4: < 6.82178e-10, 4.36922e-10, -5.62132e-10 >
v3: < -0.710294, -1.97413, -0.259628 > v4: < 4.0185, 0.383327, -0.259558 >
v3: < 0.024844, -1.90401, -0.307112 > v4: < -4.0185, -0.383327, 0.259558 >
v3: < -1.09498, 1.30431, -2.39664 > v4: < -6.84531e-10, -6.0231e-10, 4.40456e-10 >
v3: < -0.594728, 1.74448, -2.71852 > v4: < 6.84531e-10, 6.0231e-10, -4.40456e-10 >
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 338, in main
    frozen_atoms=frozen_indices,
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/coordinate_systems/internal_coordinates.py", line 133, in from_options
    return cls(cls.default_options().set_values(kwargs))
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/coordinate_systems/primitive_internals.py", line 77, in __init__
    self.get_hybrid_indices(xyz)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/coordinate_systems/primitive_internals.py", line 1277, in get_hybrid_indices
    raise RuntimeError
RuntimeError
mv: cannot stat ‘/home/guest/guest94/jianyi/AutomaticReactionDiscovery/result/*’: No such file or directory
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 838, in opt_steps
    if self.energies[self.nnodes-1]>self.energies[self.nnodes-2] and fp>0 and self.nodes[self.nnodes-1].gradrms>self.options['CONV_TOL']:
NameError: global name 'fp' is not defined
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 838, in opt_steps
    if self.energies[self.nnodes-1]>self.energies[self.nnodes-2] and fp>0 and self.nodes[self.nnodes-1].gradrms>self.options['CONV_TOL']:
NameError: global name 'fp' is not defined
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 338, in main
    frozen_atoms=frozen_indices,
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/coordinate_systems/internal_coordinates.py", line 133, in from_options
    return cls(cls.default_options().set_values(kwargs))
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/coordinate_systems/primitive_internals.py", line 77, in __init__
    self.get_hybrid_indices(xyz)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/coordinate_systems/primitive_internals.py", line 1277, in get_hybrid_indices
    raise RuntimeError
RuntimeError
mv: cannot stat ‘/home/guest/guest94/jianyi/AutomaticReactionDiscovery/result/*’: No such file or directory
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 822, in opt_steps
    ictan=self.ictan[n],
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/optimizers/eigenvector_follow.py", line 130, in optimize
    ls = self.Linesearch(nconstraints, x, fx, g, dq, step, xp,constraint_steps,self.linesearch_parameters,molecule,verbose)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/optimizers/_linesearch.py", line 10, in NoLineSearch
    xyz = molecule.coord_obj.newCartesian(molecule.xyz, x-xp,verbose=verbose)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/coordinate_systems/internal_coordinates.py", line 519, in newCartesian
    ndq = np.linalg.norm(dQ1-dQ_actual)
ValueError: operands could not be broadcast together with shapes (2304,) (48,) 
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 822, in opt_steps
    ictan=self.ictan[n],
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/optimizers/eigenvector_follow.py", line 130, in optimize
    ls = self.Linesearch(nconstraints, x, fx, g, dq, step, xp,constraint_steps,self.linesearch_parameters,molecule,verbose)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/optimizers/_linesearch.py", line 10, in NoLineSearch
    xyz = molecule.coord_obj.newCartesian(molecule.xyz, x-xp,verbose=verbose)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/coordinate_systems/internal_coordinates.py", line 519, in newCartesian
    ndq = np.linalg.norm(dQ1-dQ_actual)
ValueError: operands could not be broadcast together with shapes (2304,) (48,) 
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 838, in opt_steps
    if self.energies[self.nnodes-1]>self.energies[self.nnodes-2] and fp>0 and self.nodes[self.nnodes-1].gradrms>self.options['CONV_TOL']:
NameError: global name 'fp' is not defined
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 338, in main
    frozen_atoms=frozen_indices,
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/coordinate_systems/internal_coordinates.py", line 133, in from_options
    return cls(cls.default_options().set_values(kwargs))
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/coordinate_systems/primitive_internals.py", line 77, in __init__
    self.get_hybrid_indices(xyz)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/coordinate_systems/primitive_internals.py", line 1277, in get_hybrid_indices
    raise RuntimeError
RuntimeError
mv: cannot stat ‘/home/guest/guest94/jianyi/AutomaticReactionDiscovery/result/*’: No such file or directory
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 822, in opt_steps
    ictan=self.ictan[n],
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/optimizers/eigenvector_follow.py", line 130, in optimize
    ls = self.Linesearch(nconstraints, x, fx, g, dq, step, xp,constraint_steps,self.linesearch_parameters,molecule,verbose)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/optimizers/_linesearch.py", line 10, in NoLineSearch
    xyz = molecule.coord_obj.newCartesian(molecule.xyz, x-xp,verbose=verbose)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/coordinate_systems/internal_coordinates.py", line 519, in newCartesian
    ndq = np.linalg.norm(dQ1-dQ_actual)
ValueError: operands could not be broadcast together with shapes (2304,) (48,) 
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 822, in opt_steps
    ictan=self.ictan[n],
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/optimizers/eigenvector_follow.py", line 130, in optimize
    ls = self.Linesearch(nconstraints, x, fx, g, dq, step, xp,constraint_steps,self.linesearch_parameters,molecule,verbose)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/optimizers/_linesearch.py", line 10, in NoLineSearch
    xyz = molecule.coord_obj.newCartesian(molecule.xyz, x-xp,verbose=verbose)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/coordinate_systems/internal_coordinates.py", line 519, in newCartesian
    ndq = np.linalg.norm(dQ1-dQ_actual)
ValueError: operands could not be broadcast together with shapes (2304,) (48,) 
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 838, in opt_steps
    if self.energies[self.nnodes-1]>self.energies[self.nnodes-2] and fp>0 and self.nodes[self.nnodes-1].gradrms>self.options['CONV_TOL']:
NameError: global name 'fp' is not defined
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 822, in opt_steps
    ictan=self.ictan[n],
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/optimizers/eigenvector_follow.py", line 130, in optimize
    ls = self.Linesearch(nconstraints, x, fx, g, dq, step, xp,constraint_steps,self.linesearch_parameters,molecule,verbose)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/optimizers/_linesearch.py", line 10, in NoLineSearch
    xyz = molecule.coord_obj.newCartesian(molecule.xyz, x-xp,verbose=verbose)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/coordinate_systems/internal_coordinates.py", line 519, in newCartesian
    ndq = np.linalg.norm(dQ1-dQ_actual)
ValueError: operands could not be broadcast together with shapes (2304,) (48,) 
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 838, in opt_steps
    if self.energies[self.nnodes-1]>self.energies[self.nnodes-2] and fp>0 and self.nodes[self.nnodes-1].gradrms>self.options['CONV_TOL']:
NameError: global name 'fp' is not defined
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 838, in opt_steps
    if self.energies[self.nnodes-1]>self.energies[self.nnodes-2] and fp>0 and self.nodes[self.nnodes-1].gradrms>self.options['CONV_TOL']:
NameError: global name 'fp' is not defined
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 838, in opt_steps
    if self.energies[self.nnodes-1]>self.energies[self.nnodes-2] and fp>0 and self.nodes[self.nnodes-1].gradrms>self.options['CONV_TOL']:
NameError: global name 'fp' is not defined
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 838, in opt_steps
    if self.energies[self.nnodes-1]>self.energies[self.nnodes-2] and fp>0 and self.nodes[self.nnodes-1].gradrms>self.options['CONV_TOL']:
NameError: global name 'fp' is not defined
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 838, in opt_steps
    if self.energies[self.nnodes-1]>self.energies[self.nnodes-2] and fp>0 and self.nodes[self.nnodes-1].gradrms>self.options['CONV_TOL']:
NameError: global name 'fp' is not defined
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 822, in opt_steps
    ictan=self.ictan[n],
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/optimizers/eigenvector_follow.py", line 130, in optimize
    ls = self.Linesearch(nconstraints, x, fx, g, dq, step, xp,constraint_steps,self.linesearch_parameters,molecule,verbose)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/optimizers/_linesearch.py", line 10, in NoLineSearch
    xyz = molecule.coord_obj.newCartesian(molecule.xyz, x-xp,verbose=verbose)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/coordinate_systems/internal_coordinates.py", line 519, in newCartesian
    ndq = np.linalg.norm(dQ1-dQ_actual)
ValueError: operands could not be broadcast together with shapes (2304,) (48,) 
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 838, in opt_steps
    if self.energies[self.nnodes-1]>self.energies[self.nnodes-2] and fp>0 and self.nodes[self.nnodes-1].gradrms>self.options['CONV_TOL']:
NameError: global name 'fp' is not defined
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 822, in opt_steps
    ictan=self.ictan[n],
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/optimizers/eigenvector_follow.py", line 130, in optimize
    ls = self.Linesearch(nconstraints, x, fx, g, dq, step, xp,constraint_steps,self.linesearch_parameters,molecule,verbose)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/optimizers/_linesearch.py", line 10, in NoLineSearch
    xyz = molecule.coord_obj.newCartesian(molecule.xyz, x-xp,verbose=verbose)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/coordinate_systems/internal_coordinates.py", line 519, in newCartesian
    ndq = np.linalg.norm(dQ1-dQ_actual)
ValueError: operands could not be broadcast together with shapes (2304,) (48,) 
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused
Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/rmg_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/wrappers/main.py", line 504, in main
    gsm.go_gsm(inpfileq['max_gsm_iters'],inpfileq['max_opt_steps'],rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/de_gsm.py", line 77, in go_gsm
    self.opt_iters(max_iter=opt_iters,optsteps=opt_steps,rtype=rtype)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 283, in opt_iters
    self.opt_steps(optsteps)
  File "/home/guest/guest94/anaconda3/envs/rmg_env/lib/python2.7/site-packages/pyGSM-0.1-py2.7.egg/pygsm/growing_string_methods/base_gsm.py", line 838, in opt_steps
    if self.energies[self.nnodes-1]>self.energies[self.nnodes-2] and fp>0 and self.nodes[self.nnodes-1].gradrms>self.options['CONV_TOL']:
NameError: global name 'fp' is not defined
